name: Build and Test
on:
  - push
  - pull_request

jobs:

  tests_ember_compat:
    name: Ember Compatability
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    strategy:
      matrix:
        scenario:
        - "ember-lts-3.20"
        - "ember-lts-3.8"

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 8
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: 'pnpm'
        
    - name: Install dependencies
      run: pnpm install
    - name: Test with ${{ matrix.scenario }}
      run: pnpm run test:ember ${{ matrix.scenario }}
